flowsTotalsPlot(uah_flw)
marginDynamicsPlot(uah_flw)
flowsAbsPlot(uah_flw)
flowsTotalShares(shareDf)
flowsTypeShare(shareDf, T)
flowsTypeShare(shareDf)
flowAbsDynamicsPlot(flows_dat, "deposit eur")
flowRelDynamicsPlot(uah_flw, "deposit usd")


currencyDynamicsPlot(hold_total)
currencyPortfolioPlot(hold_total)
currencyHoldingsPlot(hold_total, "USD", "currencyDynamics")
currencyHoldingsPlot(hold_total, "EUR", "currencyDiffAbs")
currencyHoldingsPlot(hold_total, "UAH", "currencyDiffRel")
profitsPlot(hold_total)
profitErrorAbs(hold_total)
profitErrorRel(hold_total)
holdingTypesDynamicsPlot(hold_total)
holdingTypesPortfolioPlot(hold_total)
uahRatePlot(uah_rates, "USD")
currencyHoldingsPlot(hold_total, "GLD", "currencyDynamics")
currencyHoldingsPlot(hold_total, "GLD", "currencyDiffAbs")
currencyHoldingsPlot(hold_total, "GLD", "currencyDiffRel")
