name: Test Docker image

on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Build
        run: docker build -t budget-staging .
      - name: Setup Google Credentials
        env:
          GOOGLE_CREDENTIALS_FILE_URL: ${{ secrets.GOOGLE_CREDENTIALS_FILE_URL }}
        run: ./bin/setup_ci.sh
      - name: Run example spreadsheet
        env:
          SPREADSHEET_URL: "https://docs.google.com/spreadsheets/d/16TUXk_thxH8JkbdlAdFe9q8s3f6PDZiq1zXvecUp-eM/edit?usp=sharing"
          SPREADSHEET_EMAIL: "bot.pustovit@gmail.com"
          OUT_FILE: "generated-example.pdf"
          IMAGE_NAME: "budget-staging"
        run: ./bin/example_report.sh
      - name: Check generated report
        run: ./tests/test_example.sh ~/.budget/files/generated-example.pdf
      - name: Save Report to artifacts
        uses: actions/upload-artifact@v2
        with:
          name: Example_Report
          path: ~/.budget/files/generated-example.pdf